// Centralized Brand Copy & Microcopy for Cardy
// Source of truth: https://narrow-cast-25389176.figma.site/

export const CardyCopy = {
  brand: {
    name: 'Cardy',
    tagline: 'Thanh toán card đi? Để Cardy!',
    shortDesc: 'Người bạn rành thẻ tín dụng, chọn đúng chiếc card hợp với cách bạn tiêu.',
  },
  hero: {
    headlineLead: 'Thanh toán card đi?',
    headlineAccent: 'Để Cardy!',
    subheadline:
      'Thẻ tốt chưa chắc là thẻ hợp với bạn. Kể Cardy nghe bạn hay tiêu vào đâu, Cardy gợi ý vài chiếc card có benefit đúng chỗ bạn cần.',
    badge: 'Đừng chọn card đại! Để Cardy xem chooo',
    ctaPrimary: 'Tìm card hợp với bạn',
    ctaSecondary: 'So sánh card',
    trust1: 'Dữ liệu 30+ thẻ ngân hàng hàng đầu',
    trust2: 'Quyền lợi tính bằng tiền thật (VND)',
    trust3: 'Trung lập, không thiên vị ngân hàng nào',
  },
  howItWorks: {
    title: 'Cách Cardy giúp bạn',
    step1Title: '1. Kể Cardy nghe',
    step1Desc: 'Ăn ngoài, mua online hay đi xa? Chọn vài mục bạn tiêu nhiều nhất.',
    step2Title: '2. Xem card hợp gu',
    step2Desc: 'Hoàn tiền, phí thường niên và ưu đãi đối tác — đặt cạnh nhau dễ nhìn.',
    step3Title: '3. Chọn card đi',
    step3Desc: 'Ưng chiếc nào thì lưu vào ví hoặc xem chi tiết điều kiện phát hành.',
  },
  recommendation: {
    entryTitle: 'Không biết chọn card nào? Cardy xem chooo',
    entryDesc: 'Chọn khoản chi sắp thanh toán hoặc tiêu chí bạn quan tâm nhất.',
    tabPurchase: 'Đi đâu, card gì?',
    tabOpenNew: 'Tìm card mở mới',
    resultFound: 'Cardy tìm được vài chiếc hợp gu rồi.',
    heroCardLead: 'Thẻ này hợp bạn đấy!',
    whyItFits: 'Ưu đãi tại cửa hàng yêu thích & Điểm cộng:',
    honestNotes: 'Lưu ý một chút:',
    honestNotesDefault: 'Phí thường niên hơi cao — nhưng benefit chi tiêu cũng đáng xem.',
    whatYouGain: 'Bạn nhận được ước tính:',
    alternativesTitle: 'Đang phân vân? Xem thêm mấy chiếc này:',
    alternativesDesc: 'Các lựa chọn khác cũng rất đáng cân nhắc cho bạn.',
  },
  wallet: {
    title: 'Ví thẻ của bạn',
    desc: 'Xem thẻ nào nên quẹt ở đâu, theo dõi ưu đãi đang có và so thử thẻ mới.',
    tabMapping: 'Đi đâu quẹt gì',
    tabCards: 'Thẻ trong ví',
    tabSimulate: 'So thử card mới',
    tabSpending: 'Mức chi hàng tháng',
    emptyTitle: 'Chưa có card nào ở đây.',
    emptyDesc: 'Thêm vài chiếc thẻ bạn đang có trong ví để Cardy chỉ cách quẹt tối ưu nhất nhé.',
    addCardCTA: 'Thêm card vào ví',
    addSuccess: 'Lưu rồi nhé. Ưu đãi ví của bạn đã được cập nhật.',
    whatIfLead: 'Đang phân vân? So thử nhé.',
    whatIfSub: 'Thêm card này vào ví có thực sự giúp bạn nhận thêm nhiều quyền lợi hơn không?',
    spendingLead: 'Chi tiêu hàng tháng',
    spendingHint: 'Chỉ dùng để gợi ý card.',
  },
  explore: {
    title: '30+ chiếc card ngân hàng hàng đầu',
    desc: 'Biểu phí thường niên, quyền lợi hoàn tiền và điều kiện phát hành minh bạch.',
    emptyTitle: 'Chưa có card nào ở đây.',
    emptyDesc: 'Thử đổi tiêu chí xem nhé.',
    resetFilters: 'Đổi tiêu chí',
  },
  compare: {
    title: 'So sánh card',
    desc: 'Đang phân vân? So thử hai card này đặt cạnh nhau.',
    emptyTitle: 'Chưa chọn card nào để so sánh.',
    emptyDesc: 'Chọn tối đa 3 chiếc card để Cardy đặt lên bàn cân so sánh giúp bạn nhé.',
  },
  errors: {
    title: 'Ối, chưa tải được.',
    desc: 'Kiểm tra kết nối rồi thử lại nhé.',
    retry: 'Thử lại',
  },
  loading: {
    default: 'Để Cardy xem card nào hợp…',
  },
  badges: {
    bestMatch: '★ Phù hợp nhất',
    new: 'Mới',
    cashback: 'Hoàn 10%',
    zeroFee: '0đ phí năm',
    highFee: 'Phí cao',
  },
};
